### PR TITLE
Gif/complex layout support

### PR DESCRIPTION
**Pull request by katie-cb**
Allow dev define the view to be used for zooming. This will allow gif support as well as complex layout zoom support.

### CODE REVIEW

**Comment by imablanco** [comment]
This would not even work...

**Comment by katie-cb** [comment]
This is live code in my project, its been tested and working.

**Comment by katie-cb** [comment]
Did you test it?

**Comment by imablanco** [comment]
Yes I checkout the code and tested it. Did you forget tu push something else? If duplicatedTarget is passed to Builder it will crash, as the given View already has a parent.

**Comment by katie-cb** [comment]
You need to create a new view that doesn't have a parent attached, instead of reusing the view. Maybe I can add some documentations.

For example
`if (imageUrl.endsWith(".gif")) {
                val duplicate = MyImageView(itemView.context)
                // load gif
                duplicate.loadImage(imageUrl)
                builder.setTargetDuplicate(duplicate)
}`

**Comment by imablanco** [comment]
Please update the MR with an example.

**Pull request closed without merging**
