### PR TITLE
Added info to README about immersive mode.

### PR DESCRIPTION
**Pull request by AdamMc331**

### CODE REVIEW

**Comment by AdamMc331** [comment]
@imablanco Just wanted to bump this and get your thoughts. Have you had a chance to review it? Would you like me to change anything?

**Comment by imablanco** [comment]
I will be checking this along with other issues during this weekend, so I will merge it on Sunday if everything is ok. Sorry for the delay! Very busy at work right now :(

**Comment by AdamMc331** [comment]
No worries, thank you for the update!

**Comment by AdamMc331** [comment]
gah I messed up the .idea/ files when I tried to rebase this. I'll tinker with it later.

**Pull request closed without merging**
